/*
Postgres SQL
brew install postgresql
brew upgrade postgresql
postgres --version

1.Start/stop DB
sudo gem install lunchy
mkdir -p ~/Library/LaunchAgents
cp /usr/local/Cellar/postgresql/10.4/homebrew.mxcl.postgresql.plist ~/Library/LaunchAgents/
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
lunchy start postgres
lunchy stop postgres

2. Open postgres admin user
psql postgres
Quit cmd:
\q

3. Create password for Postgres:
ALTER USER postgres PASSWORD '123456'
4. Create role:
CREATE USER postgres SUPERUSER;

5. Create data:
CREATE TABLE IF NOT EXISTS lists (
	id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(40) NOT NULL CHECK (name <> ''),
    priority    integer NOT NULL,
    description text,
    duedate 	date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
	id    	integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	listId  integer REFERENCES lists(id),
	name    varchar(40) NOT NULL CHECK (name <> ''),
	isFinished boolean
);
Show all tables:
\dt
Insert data:
INSERT INTO lists(name,priority,description,duedate) VALUES
    ('make TodoList Nodejs project', 1, 'This is a training course','2018-07-24');

INSERT INTO lists(name,priority,description,duedate) VALUES
    ('make TodoList React Native project', 0, 'This is a RN training course','2018-08-25');

INSERT INTO tasks(listId,name,isFinished) VALUES
    (2, 'Make UI App in React Native', 'false');

INSERT INTO tasks(listId,name,isFinished) VALUES
    (2, 'Do some Components in React Native', 'false');

npm install --save sequelize
npm install --save pg pg-hstore
npm install -g sequelize-cli

SELECT * FROM lists WHERE name LIKE '%n%' ORDER BY id DESC;
SELECT * FROM lists WHERE name LIKE '%n%' ORDER BY id ASC;

UPDATE lists
SET priority = 3, description = 'test'
WHERE id = 4;

*/
import { app } from './app';
import { PORT } from './constants';
import { listRouter } from './routers/listRouter';
import taskRouter from './routers/taskRouter';

app.listen(PORT, () => console.log(`Server is listening on port ${PORT}`));
