data = [
    {
        name:"Siêu Thú Cuồng Nộ",
        review:"6.5 / 10 (6837)",
        link:"https://api.banhtv.com/getfb/play.php?q=U2FsdGVkX1%2FdhxfI1oKqSKqaJgpB2a6X%2B3FiOkuhs7Yca3fe17BbvSFzra7fQ5entfGrZk338Z3vxwSmi1ECDXTjNNgG9d%2F3IWlCaZoMQLFK%2Be0iE4nU%2Bco8LefE2j0E",
        img:"http://s.aphim.co/uploads/film/images/modsz/20180416/tt2231461_216_320.jpg",
        season:"1",
        eps:"1",
        content:"Rampage - Siêu Thú Cuồng Nộ nói về nhà sinh vật học Davis Okoye (Dwayne Johnson) đã kết bạn với George, một con khỉ đột thông minh, người đã được chăm sóc từ khi sinh ra. Tuy nhiên, một thí nghiệm di truyền giả mạo đã biến đổi con khỉ nhuyễn thành một con quái vật. Khi các con quái vật mới được tạo ra này tràn ngập khắp Bắc Mỹ, phá hủy mọi thứ trên con đường của họ, Okoye đã làm việc với một kỹ sư di truyền bị để tìm ra thuốc giải độc, chiến đấu để vượt qua một chiến trường luôn thay đổi, không chỉ để ngăn chặn một thảm hoạ toàn cầu mà còn cứu được sinh vật đã từng là bạn của mình. ",
        actor:"Dwayne Johnson, Jeffrey Dean Morgan, Malin Akerman, Joe Manganiello",
        director:"Brad Peyton",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Biệt Đội Siêu Anh Hùng 3: Cuộc Chiến Vô Cực ",
        review:"8.9 / 10 (301401)",
        link:"https://video.fhan5-3.fna.fbcdn.net/v/t42.9040-2/10000000_107191213478417_7480688158854610944_n.mp4?_nc_cat=0&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=1500&vabr=781&oh=efa25e3888d3e3ec8042ffc67f036b83&oe=5B2E8FB0",
        img:"http://image.phimmoi.net/film/3244/poster.medium.jpg",
        season:"1",
        eps:"1",
        content:"Sau chuyến hành trình độc nhất vô nhị không ngừng mở rộng và phát triển vụ trũ điện ảnh Marvel, bộ phim Avengers: Cuộc Chiến Vô Cực sẽ mang đến màn ảnh trận chiến cuối cùng khốc liệt nhất mọi thời đại. Biệt đội Avengers và các đồng minh siêu anh hùng của họ phải chấp nhận hy sinh tất cả để có thể chống lại kẻ thù hùng mạnh Thanos trước tham vọng hủy diệt toàn bộ vũ trụ của hắn.",
        actor:"Tessa Thompson, Chris Hemsworth, Tom Hiddleston, Scarlett Johansson",
        director:"Anthony Russo, Joe Russo",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Quái Nhân 2 ",
        review:"8.1 / 10 (132) ",
        link:"https:video.xx.fbcdn.net/v/t42.9040-2/10000000_1026051590893078_3837080471796187136_n.mp4?_nc_cat=0&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=1500&vabr=716&oh=6a5ec91dc6010298fae09b1e594ff770&oe=5B2F3E0F",
        img:"http://image.phimmoi.net/film/5001/poster.medium.jpg",
        season:"1",
        eps:"1",
        content:"Phim Quái Nhân 2 - Deadpool 2: Sau khi sống sót khỏi pha tấn công chí mạng của bò tót, một đầu bếp dị dạng (Wade Wilson) chật vật để hoàn thành ước mơ trở thành người pha chế nóng bỏng nhất của Mayberry trong khi phải quen với việc mất đi vị giác. Trong hành trình tìm lại niềm vui cuộc sống và công tắc du hành thời gian, Wade phải chiến đấu với đám ninja, Yakuza và bầy chó quyến rũ. Hắn chu du vòng quanh thế giới để khám phá tầm quan trọng của gia đình, tình bạn và mùi vị - trải nghiệm chuyến phiêu lưu mới và giành danh hiệu hằng mơ ước bấy lâu - Người Tình Tuyệt Nhất Thế GIới.",
        actor:"Morena Baccarin, Ryan Reynolds, Josh Brolin, T.J. Miller",
        director:"David Leitch",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Tomb Raider: Huyền Thoại Bắt Đầu",
        review:"6.8 / 10 (36672) ",
        link:"https://api.phimbathu.com/getfb/play.php?q=U2FsdGVkX181Tfvfsrnb28LzPGDSPqzp1DoybbRJ5YWNwIHXGyh6jSA3dgWL3EAfBRx%2FyXZwY%2FCWKurxmNCJaQu1pgkVwUo5YYTXI2l1s3Y3mm6CJ1QNYEVEfF4s5AMR",
        img:"http://image.phimmoi.net/film/6605/poster.medium.jpg",
        season:"1",
        eps:"1",
        content:"Tomb Raider: Huyền Thoại Bắt Đầu 2018 là cuộc hành trình trở thành huyền thoại của Lara Croft - con gái của nhà khảo cổ học & doanh nhân Richard Croft. Trước khi mất tích, Richard đã để lại lời nhắn cho con gái mình về hòn đảo bí ấn & tổ chức Trinity với kế hoạch hủy diệt thế giới. Hãy cùng Lara Croft vén bức màn bí mật & cứu thế giới. ",
        actor:"Alicia Vikander, Dominic West, Walton Goggins, Daniel Wu",
        director:"Roar Uthaug",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Đặc Nhiệm Siêu Anh Hùng Phần 5 ",
        review:"7.5 / 10 (60)",
        link:"https://api.bilutv.com/getfb/play.php?q=U2FsdGVkX18N%2BoJXGLWbXwk0nesTv6gVRsaNmeTUJms4KFfXclcebOe1qeWK%2FwzZSED2EhxsYd6rfXWVyLiSo0NUzaTWGKTaYNC8Q0rvh7gMAhA%2FtGLtR5jjnyCKH%2FiD",
        img:"http://s.aphim.co/uploads/film/images/modsz/20171203/17c48fa5a7d0b7b753c5cb27ada1956e_218_320.jpg",
        season:"1",
        eps:"1",
        content:"Phim Đặc Vụ S.H.I.E.L.D - Đặc Nhiệm Siêu Anh Hùng Phần 5 (2017): Lần này, Phil Coulson và nhóm của anh tỉnh dậy trên một chiếc phi thuyền đang bay ở ngoài vũ trụ. Chuyện gì đã xảy ra với họ? ",
        actor:"Clark Gregg, Chloe Bennet, Ming-Na Wen, Jason O'Mara",
        director:"Sharla Oliver",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Siêu Đại Chiến Thái Bình Dương 2: Cuộc Nổi Dậy ",
        review:"8.3 / 10 (50) ",
        link:"https://api.phimbathu.com/getfb/play.php?q=U2FsdGVkX189JJyKIbROiUd28vx6HcDEfFLHhl5MrTvWEKpO8pwBQc4Y2FdXFQJRtb5J3%2B2GOKYcbaT1P61dW%2F247L9eABiomyDjFcceSYtcXZ7rj%2FVjub3Mz%2BGCnBuN",
        img:"http://s.aphim.co/uploads/film/images/modsz/20171011/10358fbebd4ffffb827f30074ce0a221_202_320.jpg",
        season:"1",
        eps:"1",
        content:"Bối cảnh phim Siêu Đại Chiến Thái Bình Dương phần 2: Đã 10 năm kể từ trận chiến ở Breach nhưng các trận chiến trên đại dương vẫn không ngừng. Được chứng minh bằng chiến thắng tại Breach, chương tình Jaeger đã phát triển thành lực lượng phòng thủ toàn cầu mạnh nhất trong lịch sử nhân loại. PPDC hiện đang kêu gọi những người lính giỏi nhất và thông minh nhất để vươn lên trở thành thế hệ anh hùng kế tiếp. Khi mối đe dọa của Kaiju trở lại, chúng tôi sẽ sẵn sàng. ",
        actor:"Scott Eastwood, Burn Gorman, Adria Arjona, Tian Jing",
        director:" Steven S. DeKnight",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Đấu Trường Ảo ",
        review:"9 / 10 (900) ",
        link:"https://api.phimbathu.com/getfb/play.php?q=U2FsdGVkX1%2F5sdtYjXdC4AwMJKU6hdyyKDbfCMIxIr3UPRCINF7d0jKWfMriTrM%2FXiJASythdFFBcjTgk%2BO7I29Ez3PvtgejuJW0dbU8GEbEU2%2BPvwEJH1ZtbgcSguNq",
        img:"http://s.aphim.co/uploads/film/images/modsz/20171223/tt1677720_216_320.jpg",
        season:"1",
        eps:"1",
        content:"Ready Player One - Đấu Trường Ảo được dựng thành phim dựa trên tiểu thuyết cùng tên của tác giả Ernest Cline. Bộ phim lấy bối cảnh năm 2044, khi người sáng lập ra Oasis - một tựa game online, mất mạng. Khi đó, ông thách thức tất cả những người chơi Oasis đi tìm Easter Eggs - Trứng phục sinh. Phần thưởng dành cho người chiến thắng là những tài sản vô cùng quý báu mà ông để lại. Một chàng trai mang tên Wade Watts đã tìm ra được những gợi ý đầu tiên trong cuộc tìm kiếm và bắt đầu hành trình của mình. ",
        actor:"Olivia Cooke, Hannah John-Kamen, T.J. Miller, Ben Mendelsohn",
        director:"Steven Spielberg",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Cuộc Di Tản",
        review:"8.3 / 10 (259800) ",
        link:"https://video.fhan5-6.fna.fbcdn.net/v/t42.9040-2/10000000_212444919522402_4490990990663876608_n.mp4?_nc_cat=0&efg=eyJybHIiOjE1NDYsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=1546&vabr=1031&oh=a65a1a1b5dc70406fbd74b471c2e323e&oe=5B2FF7B3",
        img:"http://image.phimmoi.net/film/4851/poster.medium.jpg",
        season:"1",
        eps:"1",
        content:"Bối cảnh trong phim Cuộc Di Tản nói về trận chiến Dunkirk diễn ra từ ngày 26/5 - 4/6/1940 ở thành phố Dunkirk (hoặc Dunkerque) của nước Pháp, là một trong những trận chiến ác liệt nhất thời điểm này, giữa quân Đồng Minh và Đức Quốc Xã, do đó đây còn gọi là Trận Chiến nước Pháp. Ở trận này, quân Đức đã chiếm đóng nước Pháp và vây hãm liên quân của Bỉ, Canada, Anh và Pháp, đánh cho quân Đồng Minh thua tơi tả và phải mở đường máu theo phía eo biển để rút về nước Anh. ",
        actor:"Tom Hardy, Cillian Murphy, Mark Rylance, Kenneth Branagh",
        director:"Christopher Nolan",
        category:"Phim Hot",
        country:"Mỹ",
    },
    {
        name:"Ba Biển Quảng Cáo Ngoài Trời ở Missouri ",
        review:" 8.3 / 10 (62375) ",
        link:"https://video.fsgn5-5.fna.fbcdn.net/v/t42.9040-2/10000000_164344240948609_8360042262708617216_n.mp4?_nc_cat=0&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=1500&vabr=517&oh=8800df340b871ea59871f16df9992ae3&oe=5B2EC603",
        img:"http://s.aphim.co/uploads/film/images/modsz/20180126/tt5027774_216_320.jpg",
        season:"1",
        eps:"1",
        content:"Three Billboards Outside Ebbing, Missouri là tác phẩm thuộc thể loại hình sự pha hài do Martin McDonagh đạo diễn, kể về hành trình của một người mẹ đòi lại công lý sau khi cảnh sát không tìm được nghi phạm trong vụ sát hại con cô. Cô thuê ba tấm bảng quảng cáo trên đường để ghi nội dung bày tỏ sự phẫn uất với chính quyền. Phim nhận 93% đánh giá tích cực trên Rotten Tomatoes với điểm trung bình 8,6. ",
        actor:"Frances McDormand, Caleb Landry Jones, Kerry Condon, Sam Rockwell",
        director:"Martin McDonagh",
        category:"Phim Hot",
        country:"Mỹ",
     },

    ]